services:
  db-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_empresas_test
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql
