"""init

Revision ID: 3e03f2cf94fe
Revises: 
Create Date: 2026-06-25 15:32:56.642506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e03f2cf94fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('codigo_empresa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo_scrum', sa.String(length=100), nullable=True),
    sa.Column('usuario_admin_dpd', sa.Integer(), nullable=True),
    sa.Column('web', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigo_empresa')
    )
    op.create_table('empresa_servicios',
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.Column('servicio', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('codigo_empresa', 'servicio')
    )
    op.create_table('usuario',
    sa.Column('codigo_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.Enum('admin_total', 'admin_empresa', 'usuario', name='rol_enum'), nullable=False),
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('codigo_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('documentos',
    sa.Column('id_documento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.Column('usuario_subio', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_documento', sa.Enum('DPD', 'ISO', name='tipo_doc_enum'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_subio'], ['usuario.codigo_usuario'], ),
    sa.PrimaryKeyConstraint('id_documento')
    )
    op.create_table('fichajes',
    sa.Column('id_fichaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.Column('codigo_usuario', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(), nullable=False),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['codigo_usuario'], ['usuario.codigo_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_fichaje')
    )
    op.create_table('tareas',
    sa.Column('codigo_tarea', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('asignacion', sa.Integer(), nullable=True),
    sa.Column('columna', sa.Enum('Todo', 'Haciendose', 'En revision', 'Done', name='columna_enum'), nullable=True),
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion'], ['usuario.codigo_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('codigo_tarea')
    )
    op.create_table('tickets',
    sa.Column('id_reporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_usuario', sa.Integer(), nullable=False),
    sa.Column('nivel_importancia', sa.Enum('Baja', 'Media', 'Alta', 'Critica', name='importancia_enum'), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('codigo_empresa', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Leido', 'Respondido', 'Cerrado', name='estado_ticket_enum'), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['codigo_empresa'], ['empresa.codigo_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['codigo_usuario'], ['usuario.codigo_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reporte')
    )
    op.create_table('documento_permisos',
    sa.Column('id_documento', sa.Integer(), nullable=False),
    sa.Column('codigo_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_usuario'], ['usuario.codigo_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_documento'], ['documentos.id_documento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_documento', 'codigo_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_permisos')
    op.drop_table('tickets')
    op.drop_table('tareas')
    op.drop_table('fichajes')
    op.drop_table('documentos')
    op.drop_table('usuario')
    op.drop_table('empresa_servicios')
    op.drop_table('empresa')
    # ### end Alembic commands ###
