"""add_ticket_respuesta

Revision ID: 4aa137b79dcc
Revises: b2c3d4e5f6a7
Create Date: 2026-06-29 16:37:45.200067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa137b79dcc'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('respuesta', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('fecha_respuesta', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'fecha_respuesta')
    op.drop_column('tickets', 'respuesta')
    # ### end Alembic commands ###
